# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: dart
    targetDirectory: .
    compress: true
    format: plaintext
    sources:
      - src/dart-common.txt
    sort: true
