# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: en_US
    sources:
      - src/additional_words.txt
      - src/acronyms.txt
      - src/aoo-mozilla-en-dict/en_US.dic
      - src/contractions-and-possessives.txt
      - src/en_US.txt
      - src/hunspell/en_US-large.dic
      - src/hyphenated-words.txt
      - node_modules/@cspell/dict-en-shared/src/shared-additional-words.txt
    format: trie3
    targetDirectory: '.'
    generateNonStrict: true
    excludeWordsFrom:
      - node_modules/@cspell/dict-en-shared/src/exclude-words.txt
checksumFile: true
