# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: custom_scientific_US
    targetDirectory: dict
    compress: true
    keepUncompressed: true
    format: trie3
    sources:
      - src/custom_scientific_US.dic.txt
      - src/additional_words.txt
    generateNonStrict: true

  - name: mathematics_US
    targetDirectory: dict
    compress: true
    keepUncompressed: true
    format: plaintext
    sources:
      - src/mathematics.txt
    generateNonStrict: false

checksumFile: true
