# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: 'gdscript'
    sources:
      - filename: 'src/gdscript-words/gdscript.txt'
        split: true
        allowedSplitWords:
          - ../en_US/en_US.trie
          - ../software-terms/dict/softwareTerms.txt
      - filename: 'src/gdscript.txt'
        split: true
        allowedSplitWords:
          - ../en_US/en_US.trie
          - ../software-terms/dict/softwareTerms.txt
    format: 'plaintext'
    targetDirectory: './dict'
    generateNonStrict: false
    compress: false
checksumFile: true
