# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json
targets:
  - name: rust
    targetDirectory: ./dict
    compress: true
    keepUncompressed: true
    format: plaintext
    sources:
      - src/rust.txt
    sort: true
  - name: crates
    targetDirectory: ./dict
    compress: true
    keepUncompressed: true
    format: plaintext
    sources:
      - src/crates.txt
    sort: true
keepRawCase: true
