# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: bg_BG
    sources:
      - listFile: ./source-files.txt
    format: trie3
    targetDirectory: "./dict"
    generateNonStrict: true
