# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: Czech
    sources:
      - src/Czech.dic
    format: trie3
    targetDirectory: "."
    generateNonStrict: true
