# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json
targets:
  - name: win32
    targetDirectory: dict
    compress: true
    keepUncompressed: true
    format: plaintext
    sources:
      - src/generator/win32.txt
      - src/additional-terms.txt
    sort: true
keepRawCase: true
