# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: 'km-kh'
    sources:
      - filename: 'src/km.dic'
        maxDepth: 1 # This is set to 1 to prevent initial builds from taking too long.
    format: 'trie3'
    targetDirectory: './dict'
    generateNonStrict: true
    compress: false
checksumFile: true
