# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json
targets:
  - name: npm
    targetDirectory: ./dict
    compress: false
    format: plaintext
    sources:
      - filename: src/npm.txt
        split: true
        allowedSplitWords:
          - ../en_US/en_US.trie
          - ../software-terms/dict/softwareTerms.txt
      - src/npm-keywords.txt
      - src/tools.txt
      - src/imports.txt
    sort: true
