# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json
targets:
  - name: csharp
    targetDirectory: dict
    compress: true
    keepUncompressed: true
    format: plaintext
    sources:
      - src/csharp.txt
    sort: true
split: true
