# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: en_AU
    sources:
      - ./src/additional_words.txt
      - ./src/aoo-mozilla-en-dict/en_AU.dic
      - ./src/hunspell-en_AU-large/en_AU-large.dic
      - ./node_modules/@cspell/dict-en-shared/src/shared-additional-words.txt
    format: trie3
    targetDirectory: '.'
    generateNonStrict: true
    excludeWordsFrom:
      - node_modules/@cspell/dict-en-shared/src/exclude-words.txt
checksumFile: true
