# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: html
    sources:
      - src/html.txt
      - src/svg.txt
    format: plaintext
    targetDirectory: "dict"
    generateNonStrict: false
