# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: bash-words
    sources:
      - listFile: ./common-source-files.txt
      - ./src/shell-bash-words.txt
    format: plaintext
    targetDirectory: "./dict"
    generateNonStrict: false
  - name: shell-all-words
    sources:
      - listFile: ./common-source-files.txt
      - ./src/shell-bash-words.txt
      - ./src/shell-zsh-words.txt
    format: plaintext
    targetDirectory: "./dict"
    generateNonStrict: false
