# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: docker-words
    targetDirectory: dict
    compress: true
    keepUncompressed: true
    format: plaintext
    sources:
      - src/docker-words.txt
    sort: true
