# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: bash-words
    sources:
      - ./src/bash-words.txt
    format: plaintext
    targetDirectory: "./dict"
    generateNonStrict: false
