# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: 'softwareTerms'
    sources:
      - filename: src/coding-terms.txt
        split: true
      - filename: src/cybersecurity-terms.txt
        split: true
      - filename: src/software-terms.txt
        split: true
      - filename: src/software-tools.txt
        split: true
    format: plaintext
    targetDirectory: './dict'
    generateNonStrict: false
    compress: false
  - name: 'networkingTerms'
    sources:
      - filename: src/network-os.txt
        split: true
      - filename: src/network-protocols.txt
        split: true
    format: plaintext
    targetDirectory: './dict'
    generateNonStrict: false
    compress: false
  - name: 'webServices'
    sources:
      - filename: src/software-services.txt
        split: true
    format: plaintext
    targetDirectory: './dict'
    generateNonStrict: false
    compress: false
  - name: 'computing-acronyms'
    sources:
      - filename: src/computing-acronyms.txt
        split: true
    format: plaintext
    targetDirectory: './dict'
    generateNonStrict: false
    compress: false
