name: Lint
on:
  pull_request:
    paths:
      - ".eslint*"
      - .prettier*"
      - "**/*.js"
      - "**/*.md"
      - "**/*.json"
      - "**/*.yml"
      - "**/*.yaml"
  push:
    paths:
      - ".eslint*"
      - .prettier*"
      - "**/*.js"
      - "**/*.md"
      - "**/*.json"
      - "**/*.yml"
      - "**/*.yaml"
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Restore CSpell cache
        uses: actions/cache@v2
        with:
          key: cspell-cache-${{ runner.os }}-lint-${{ hashFiles('**/*.ts', '**/*.md') }}
          path: |
            .cspellcache
          restore-keys: |
            cspell-cache-${{ runner.os }}-lint-
            cspell-cache-${{ runner.os }}-

      - run: yarn
      - run: yarn run lint-ci
