name: ' ðŸ¤– Update Dependabot'

on:
  workflow_dispatch:
    inputs:
      base:
        description: The Base Ref to apply the diff
        required: false
        default: 'main'

  schedule:
    - cron: '0 12 * * *'

permissions:
  contents: read

jobs:
  update-dependabot:
    runs-on: ubuntu-latest
    env:
      NEW_BRANCH: update-dependabot-${{ inputs.base || 'main' }}
      REF_BRANCH: ${{ inputs.base || 'main' }}
      PR_TYPE: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          ref: ${{ env.REF_BRANCH }}

      - name: Setup
        uses: ./.github/actions/quick-setup

      - name: Run Action
        id: dependabot
        uses: streetsidesoftware/actions/public/update-dependabot-github-actions@v1
        with:
          prefix: ci

      - name: Echo Result
        env:
          SUMMARY: ${{ steps.dependabot.outputs.summary }}
        run: |
          echo "$SUMMARY"

      - name: Prettier
        run: |
          pnpm i
          pnpm prettier .github/dependabot.yaml --write

      - name: PR
        uses: streetsidesoftware/actions/.github/actions/pr@v1
        with:
          commit-message: '${{ env.PR_TYPE }}: Workflow Bot -- Update dependabot.yml'
          branch: ${{ env.NEW_BRANCH }}
          base: ${{ env.REF_BRANCH }}
          title: '${{ env.PR_TYPE }}: Workflow Bot -- Update dependabot.yml (${{ env.REF_BRANCH }})'
          body: ${{ steps.dependabot.outputs.summary }}
          app_id: ${{ secrets.AUTOMATION_APP_ID }}
          app_private_key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}
